apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kubernetes\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: ms-sql-server
  name: ms-sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-sql-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kubernetes\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: ms-sql-server
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Express
        - name: SA_PASSWORD
          value: Pa55w0rd2019
        image: dockermicroserv/microservdatabase:latest
        name: ms-sql-server
        ports:
        - containerPort: 1433
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
