apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kubernetes\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-sql-server
  name: ms-sql-server
spec:
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
  selector:
    io.kompose.service: ms-sql-server
status:
  loadBalancer: {}
